/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.dropdown-toggle[_ngcontent-%COMP%]{\r\n    width: 30px;\r\n    height: 30px;\r\n    cursor: pointer;\r\n}\r\n\r\n.dropdown-toggle[_ngcontent-%COMP%]::after{\r\n    display: none;\r\n}\r\n\r\n\r\n.color-picker-box[_ngcontent-%COMP%]{\r\n    display: flex;\r\n    flex-direction: row;\r\n}\r\n\r\n.color-picker-item[_ngcontent-%COMP%]{\r\n    cursor: pointer;\r\n    border: 1px solid #dcdcdc;\r\n    border-radius:5px; \r\n    min-width: 25px;\r\n    min-height: 25px;\r\n    margin: 3px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovd29yay9jYXNlL2FuZ3VsYXItc3R1ZHkvYW5ndWxhci1tb2R1bGUtc3RhcnRlci9zcmMvdG9nZ2xlLWNvbG9yLXBpY2tlci9jb2xvci1waWNrZXIvY29sb3ItcGlja2VyLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovd29yay9jYXNlL2FuZ3VsYXItc3R1ZHkvYW5ndWxhci1tb2R1bGUtc3RhcnRlci9zcmMvdG9nZ2xlLWNvbG9yLXBpY2tlci9jb2xvci1waWNrZXIvY29sb3ItcGlja2VyLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
