/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './toggle-color-picker.module';
import * as i2 from '../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as i3 from '../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as i4 from '../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as i5 from '../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as i6 from '../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as i7 from '../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as i8 from '../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as i9 from '@angular/common';
import * as i10 from '@angular/forms';
import * as i11 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as i12 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as i13 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as i14 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as i15 from '@ng-bootstrap/ng-bootstrap/buttons/buttons.module';
import * as i16 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as i17 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as i18 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as i19 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as i20 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as i21 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as i22 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as i23 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as i24 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as i25 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as i26 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as i27 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as i28 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as i29 from '@ng-bootstrap/ng-bootstrap/index';
export const ToggleColorPickerModuleNgFactory:i0.NgModuleFactory<i1.ToggleColorPickerModule> = i0.ɵcmf(i1.ToggleColorPickerModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.NgbAlertNgFactory,i3.NgbDatepickerNgFactory,i4.NgbModalBackdropNgFactory,
              i5.NgbModalWindowNgFactory,i6.NgbPopoverWindowNgFactory,i7.NgbTooltipWindowNgFactory,
              i8.NgbTypeaheadWindowNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i9.NgLocalization,i9.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i10.ɵi,i10.ɵi,([] as any[])),i0.ɵmpd(4608,i11.NgbModal,i11.NgbModal,
              [i0.ComponentFactoryResolver,i0.Injector,i12.NgbModalStack]),i0.ɵmpd(512,
              i9.CommonModule,i9.CommonModule,([] as any[])),i0.ɵmpd(512,i13.NgbAccordionModule,
              i13.NgbAccordionModule,([] as any[])),i0.ɵmpd(512,i14.NgbAlertModule,
              i14.NgbAlertModule,([] as any[])),i0.ɵmpd(512,i15.NgbButtonsModule,i15.NgbButtonsModule,
              ([] as any[])),i0.ɵmpd(512,i16.NgbCarouselModule,i16.NgbCarouselModule,
              ([] as any[])),i0.ɵmpd(512,i17.NgbCollapseModule,i17.NgbCollapseModule,
              ([] as any[])),i0.ɵmpd(512,i10.ɵba,i10.ɵba,([] as any[])),i0.ɵmpd(512,
              i10.FormsModule,i10.FormsModule,([] as any[])),i0.ɵmpd(512,i18.NgbDatepickerModule,
              i18.NgbDatepickerModule,([] as any[])),i0.ɵmpd(512,i19.NgbDropdownModule,
              i19.NgbDropdownModule,([] as any[])),i0.ɵmpd(512,i20.NgbModalModule,
              i20.NgbModalModule,([] as any[])),i0.ɵmpd(512,i21.NgbPaginationModule,
              i21.NgbPaginationModule,([] as any[])),i0.ɵmpd(512,i22.NgbPopoverModule,
              i22.NgbPopoverModule,([] as any[])),i0.ɵmpd(512,i23.NgbProgressbarModule,
              i23.NgbProgressbarModule,([] as any[])),i0.ɵmpd(512,i24.NgbRatingModule,
              i24.NgbRatingModule,([] as any[])),i0.ɵmpd(512,i25.NgbTabsetModule,i25.NgbTabsetModule,
              ([] as any[])),i0.ɵmpd(512,i26.NgbTimepickerModule,i26.NgbTimepickerModule,
              ([] as any[])),i0.ɵmpd(512,i27.NgbTooltipModule,i27.NgbTooltipModule,
              ([] as any[])),i0.ɵmpd(512,i28.NgbTypeaheadModule,i28.NgbTypeaheadModule,
              ([] as any[])),i0.ɵmpd(512,i29.NgbModule,i29.NgbModule,([] as any[])),
          i0.ɵmpd(512,i1.ToggleColorPickerModule,i1.ToggleColorPickerModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovd29yay9jYXNlL2FuZ3VsYXItc3R1ZHkvYW5ndWxhci1tb2R1bGUtc3RhcnRlci9zcmMvdG9nZ2xlLWNvbG9yLXBpY2tlci90b2dnbGUtY29sb3ItcGlja2VyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi93b3JrL2Nhc2UvYW5ndWxhci1zdHVkeS9hbmd1bGFyLW1vZHVsZS1zdGFydGVyL3NyYy90b2dnbGUtY29sb3ItcGlja2VyL3RvZ2dsZS1jb2xvci1waWNrZXIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
